"""creating the products table

Revision ID: 1caace4bc739
Revises: 
Create Date: 2026-01-03 05:18:32.568296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1caace4bc739'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_created_at', sa.DateTime(), nullable=False),
    sa.Column('project_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_title'), 'projects', ['project_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_title'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
