"""creating tables

Revision ID: 37fe8ec7b697
Revises: 
Create Date: 2026-01-05 10:33:16.088390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37fe8ec7b697'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('project_created_at', sa.DateTime(), nullable=False),
    sa.Column('project_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_title'), 'projects', ['project_title'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirm_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_project_title'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
