"""changing the user model

Revision ID: 3a79f489ac83
Revises: 37fe8ec7b697
Create Date: 2026-01-06 09:50:59.833718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a79f489ac83'
down_revision: Union[str, Sequence[str], None] = '37fe8ec7b697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
